# The Folding@Home project values, you might want to overwrite user and team.
#
# It relies on the docker image by https://docs.linuxserver.io/images/docker-foldingathome/
# If you have your own user or team, override the values below. You can also
# enable/disable gpus, smp, etc.
foldingathome:
  image: lscr.io/linuxserver/foldingathome
  kind: StatefulSet
  config:
    gpu: false
    passkey: ''
    allow: "127.0.0.1 192.168.1.0/24 10.42.0.0/16"
    web-allow: "127.0.0.1 192.168.1.0/24 10.42.0.0/16"
    power: "full"
    smp: "true"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/arch
              operator: NotIn
              values:
                - arm
                - arm64
            - key: node-role.kubernetes.io/control-plane
              operator: DoesNotExist
  priorityClassName: vlow-priority
  replicas: 4
  resources:
    requests:
      cpu: 1
      memory: "1048Mi"
    limits:
      cpu: 4
      memory: "2560Mi"

service:
  enabled: true
  ingressClassName: nginx
  labelName: my.app/hostname
  labelValue: folding
  hostName: folding.example.com

# Horizontal pod auto scaler configuration. The goal is to backfill the
# cluster with folding@home workloads, so we use an hpa resource with a very high
# number of max replicas (max replicas is currently mandatory).
#
# vlow-priority should be set to < -10, so that the cluster auto-scaler does
# not take them into account.
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPU: 90

# A set of predefined priorities for your cluster.
# If you can drop if you already manage priorities yourself, otherwise this
# will setup a default one and a very low priority which is used by the
# workloads (enabling preemption).
priority:
  - name: default-priority
    value: 100000
    default: true
  - name: vlow-priority
    value: -100000

