foldingathome:
  config:
    gpu: true
    smp: false # disables CPU slots completely, guarantees better GPU efficiency
  # you can also pass the slots explicitly
  #slots:
  #  0: "GPU"
  nodeSelector:
    node-role.kubernetes.io/gpu: "true"
  resources:
    limits:
      nvidia.com/gpu: 1
