{{ if .Values.highpriodemo.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: highprio
  name: highprio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: highprio
  namespace: highprio
  labels:
    app: highprio
spec:
  replicas: {{ .Values.highpriodemo.replicas }}
  selector:
    matchLabels:
      app: highprio
  template:
    metadata:
      labels:
        app: highprio
    spec:
      priorityClassName: default-priority
      terminationGracePeriodSeconds: 1
      containers:
      - name: highprio
        image: alpine
        command: ["dd", "if=/dev/zero", "of=/dev/null"]
        resources:
          limits:
            cpu: {{ .Values.highpriodemo.cpu }}
            memory: {{ .Values.highpriodemo.memory }}
          requests:
            cpu: {{ .Values.highpriodemo.cpu }}
            memory: {{ .Values.highpriodemo.memory }}
{{ end }}
